steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/twine', '.']

# Print version information.
- name: 'gcr.io/$PROJECT_ID/twine'
  args: ['--version']

images:
  - 'gcr.io/$PROJECT_ID/twine'
