apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: test-name
spec:
  componentKinds:
  - group: core
    kind: Service
  - group: extensions
    kind: Deployment
  descriptor:
    links:
    - description: My Description
      url: https://my-link.com
    - description: "1234"
      url: "5678"
    type: test-type
    version: test-version
  selector:
    matchLabels:
      foo: bar
