# In this directory, run the following command to build this builder.
# $ gcloud builds submit

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--pull', '--tag=gcr.io/$PROJECT_ID/gsutil','--tag=europe-docker.pkg.dev/$PROJECT_ID/ga/v1/gsutil','--tag=asia-docker.pkg.dev/$PROJECT_ID/ga/v1/gsutil','--tag=us-docker.pkg.dev/$PROJECT_ID/ga/v1/gsutil', '.']
- name: 'gcr.io/$PROJECT_ID/gsutil'
  args: ['version']

# Invoke a command that requires auth, to check that it gets piped through
# correctly.
- name: 'gcr.io/$PROJECT_ID/gsutil'
  args: ['ls']

images: ['gcr.io/$PROJECT_ID/gsutil','europe-docker.pkg.dev/$PROJECT_ID/ga/v1/gsutil','asia-docker.pkg.dev/$PROJECT_ID/ga/v1/gsutil','us-docker.pkg.dev/$PROJECT_ID/ga/v1/gsutil']
