apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: test-app
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    app.kubernetes.io/name: my-app
  name: test-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
        app.kubernetes.io/managed-by: gcp-cloud-build-deploy
        app.kubernetes.io/name: my-app
    spec:
      containers:
      - image: gcr.io/cbd-test/test-app:latest
        name: test-app


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-app
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    app.kubernetes.io/name: my-app
  name: test-app
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: test-app
  type: LoadBalancer


---

apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
    app.kubernetes.io/name: my-app
  name: my-app
  namespace: default
spec:
  componentKinds:
  - group: core
    kind: Service
  - group: extensions
    kind: Deployment
  descriptor:
    links:
    - description: My description 1
      url: https://foo.com/bar
    - description: My description 2
      url: https://asdf.com
    type: my-app
  selector:
    matchLabels:
      app.kubernetes.io/name: my-app
