steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  args: ["build", "-t", "$_IMAGE_NAME:$_IMAGE_VERSION", ".", "-f", "$_DOCKERFILE_PATH"]
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push'
  args: ["push", "$_IMAGE_NAME:$_IMAGE_VERSION"]
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  id: 'Prepare deploy'
  args:
  - 'prepare'
  - '--image=$_IMAGE_NAME:$_IMAGE_VERSION'
  - '--expose=80'
  - '--app=$_K8S_APP_NAME'
  - '--version=$_IMAGE_VERSION'
  - '--namespace=$_K8S_NAMESPACE'
  - '--label=$_K8S_LABELS,gcb-build-id=$BUILD_ID'
- name: 'gcr.io/cloud-builders/gsutil'
  id: 'Save suggested base configs and expanded configs to bucket'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
    set -e
    gsutil cp -r output/suggested gs://$_OUTPUT_BUCKET/$BUILD_ID/suggested
    echo "Copied suggested base configs to gs://$_OUTPUT_BUCKET/$BUILD_ID/suggested"
    gsutil cp -r output/expanded gs://$_OUTPUT_BUCKET/$BUILD_ID/expanded
    echo "Copied expanded configs to gs://$_OUTPUT_BUCKET/$BUILD_ID/expanded"
- name: 'gcr.io/cloud-builders/gke-deploy:stable'
  id: 'Apply deploy'
  args:
  - 'apply'
  - '--filename=output/expanded'
  - '--namespace=$_K8S_NAMESPACE'
  - '--cluster=$_GKE_CLUSTER'
  - '--location=$_GKE_LOCATION'
images:
- '$_IMAGE_NAME:$_IMAGE_VERSION'
substitutions:
  _DOCKERFILE_PATH: Dockerfile
  _IMAGE_NAME:
  _IMAGE_VERSION:
  _GKE_CLUSTER:
  _GKE_LOCATION:
  _K8S_APP_NAME:
  _K8S_NAMESPACE:
  _K8S_LABELS:
  _OUTPUT_BUCKET:
options:
  substitution_option: 'ALLOW_LOOSE'
tags: ['gcp-cloud-build-deploy', '$_K8S_APP_NAME']
