apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: test-app
spec:
  componentKinds:
  - group: apps
    kind: Deployment
  descriptor:
    type: test-app
  selector:
    matchLabels:
      app.kubernetes.io/name: test-app
