# In this directory, run the following command to build this builder.
# $ gcloud builds submit

steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/GoogleCloudPlatform/aactl']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - -c
  - |
    cd aactl/
    make image
    docker tag aactl:latest gcr.io/$PROJECT_ID/aactl:$(cat .version)
    docker tag aactl:latest gcr.io/$PROJECT_ID/aactl:latest
images:
- 'gcr.io/$PROJECT_ID/aactl'

